# Generated by Django 2.1.2 on 2018-12-18 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Json',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('json', models.FileField(upload_to='json/')),
                ('results', models.FileField(upload_to='results/')),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('active', models.BooleanField(default=False)),
                ('firstTitle', models.TextField(default='Ищешь будущую профессию в IT?')),
                ('firstDescription', models.TextField(default="поможет тебе в этом непростом выборе. Пройди небольшой тест и узнай какие направления <a class='mainLink' href='https://vk.com/fit.mospolytech'>FIT'a</a> подходят именно тебе!")),
                ('lastTitle', models.TextField(default='Ты похож на политеховца ))')),
                ('lastDescription', models.TextField(default='Тебе подойдут направления:')),
                ('background', models.FileField(upload_to='background/')),
                ('logo', models.FileField(upload_to='logo/')),
                ('questions', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='careerGuidance.Json')),
            ],
        ),
    ]
