# Generated by Django 2.1.2 on 2018-12-18 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerGuidance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='count',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='setting',
            name='background',
            field=models.FileField(upload_to='img/'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='logo',
            field=models.FileField(upload_to='img/'),
        ),
    ]
