# Generated by Django 2.1.2 on 2018-12-19 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerGuidance', '0002_auto_20181218_1445'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referer', models.CharField(max_length=255)),
                ('userAgent', models.CharField(max_length=255)),
                ('time', models.CharField(max_length=255)),
                ('results', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='json',
            name='results',
            field=models.FileField(upload_to='json/'),
        ),
    ]
