# Generated by Django 2.1.2 on 2018-12-19 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('careerGuidance', '0003_auto_20181220_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='statistic',
            name='time',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
